openapi: 3.0.2
info:
  title: train Demo
  version: "1.0.0"
paths:
  /users:
    get:
      description: Get all users
      responses:
        '200':
          description: Gets an array of users
          content:
            application/json:
             schema:
              type: array
              items:
                $ref: '#/components/schemas/User'
  /user:
    get:
      description: Get user
      responses:
        '200':
          description: Gets a users
          content:
            application/json:
             schema:
               $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      properties:
        name:
          type: string
        id:
          type: integer
